### ISSUE TITLE
Invalid X-axis rotation & actor animation issues

### ISSUE THREAD

**Issue by janEntikan** [Moguri/pman#12]
All instanced objects and lights have 90 degrees of rotation added to the X-axis.
Bones and their animation are faulty too. Perhaps related?

[blends.zip](https://github.com/Moguri/pman/files/3026036/blends.zip)

**Comment by janEntikan** [comment]
[qboy.blend.zip](https://github.com/Moguri/pman/files/3041142/qboy.blend.zip)
I'm adding an actor that makes the problem with bones more obvious.

**Comment by Moguri** [comment]
The rotation issue is now fixed upstream in blend2bam. The qboy file needs a root bone as per [this blendergltf](https://github.com/Kupoman/blendergltf/issues/121) issue.

**Comment by Moguri** [comment]
Closing this for now, feel free to re-open it (or file new bugs against blend2bam) if you still run into issues.
